dist: trusty
language: node_js
node_js:
  - "7"
os:
  - osx

after_success:
  - npm run dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
      secure: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*.zip"
    - "dist/K8s*.dmg"
  on:
    tags: false