osx_image: xcode10
dist: trusty
language: node_js
node_js:
  - "11"
os:
  - osx
sudo: required

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install yarn
  - yarn add electron-builder --dev

after_success:
  - sh set_tags.sh
  - yarn run test
  - yarn pack

script:
  - echo "Deploy mac version to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn pack; fi

notifications:
  email: false

deploy:
  provider: releases
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  name: K8sAutomation $TRAVIS_TAG
  api_key:
      secure: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*release*.zip"
    - "dist/mac/K8s*release*.zip"
    - "dist/K8s*release*.dmg"
    - "dist/mac/K8s*release*.dmg"
  on:
    branch: master
    repo: mlongarai/K8sAutomation
    tags: true