dist: trusty
language: node_js
node_js:
  - "7"
os:
  - osx

after_success:
  - npm run dist
  - sh set_tags.sh

deploy:
  provider: releases
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  name: K8sAutomation $TRAVIS_TAG
  api_key:
      secure: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*release*.zip"
    - "dist/K8s*release*.dmg"
  on:
    tags: true