dist: trusty
language: node_js
node_js:
  - "7"
os:
  - osx

before_install:
  - npm i electron-installer-dmg --save-dev

install: true

after_success:
  - sh set_tags.sh
  - npm run dist
  - npm run app
  - npm run dmg

notifications:
  email: false
  
deploy:
  provider: releases
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  name: K8sAutomation $TRAVIS_TAG
  api_key:
      secure: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*release*.zip"
    - "dist/mac/K8s*release*.zip"
    - "dist/K8s*release*.dmg"
    - "dist/mac/K8s*release*.dmg"
  on:
    branch: master
    repo: mlongarai/K8sAutomation
    tags: true