osx_image: xcode10.2

sudo: required

language: node_js
node_js: "11"

os:
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  chrome: stable # have Travis install chrome stable.

install:
  - brew install yarn
  - yarn

script:
- echo "Deploy mac version to GitHub"
- yarn release:mac