dist: trusty
language: node_js
node_js:
  - "7"
os:
  - osx

after_success:
  - npm run dist
  - export LAST_GIT_TAG_VERSION=$(git describe --abbrev=0 --tags) && export LAST_GIT_TAG_VERSION=${LAST_GIT_TAG_VERSION:1}
  - export GIT_TAG_VERSION=$((LAST_GIT_TAG_VERSION+1))

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*.zip"
    - "dist/K8s*.dmg"
  on:
    tags: false
    upload-dir: ${TRAVIS_TAG:1}