dist: trusty
language: node_js
node_js:
  - "11"
os:
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - brew install yarn
  - npm i -g yarn
  - yarn
  - npm install electron-builder
  - npm install ajv-keywords
  - npm install jquery
  - npm install electron-is

after_success:
  - sh set_tags.sh
  - npm run dist

notifications:
  email: false

deploy:
  provider: releases
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  name: K8sAutomation $TRAVIS_TAG
  api_key:
      secure: $GH_TOKEN
  file_glob: true
  file:
    - "README.md"
    - "dist/K8s*release*.zip"
    - "dist/mac/K8s*release*.zip"
    - "dist/K8s*release*.dmg"
    - "dist/mac/K8s*release*.dmg"
  on:
    branch: master
    repo: mlongarai/K8sAutomation
    tags: true